### ISSUE TITLE
Open Source Licensing?

### ISSUE THREAD

**Issue by droidicus** [lhelontra/tensorflow-on-arm#1]
I found this project today, and it was exactly what I was hoping for. Very happy that someone went through the effort to fix the tensorflow build for cross compilation!

I have a couple of issues and potential PRs for this project, but I was wondering if you would be willing to license this under an open license before I contribute. A license similar to the https://github.com/samjabrahams/tensorflow-on-raspberry-pi project, or something equally permissive, would be ideal.

Thanks again!

**Comment by droidicus** [comment]
Ah, I just saw the license comment in `build_tensorflow.sh`, might be nice if it was in a separate `LICENSE` file in the root of the project instead for clarity.

**Comment by lhelontra** [comment]
@droidicus i just added license file, thanks for your suggestions.
