### ISSUE TITLE
support for newer debians? ( please )

### ISSUE THREAD

**Issue by danFromTelAviv** [lhelontra/tensorflow-on-arm#11]
Hi,
This is a great project. I actually thought of doing this and then my friend told me to see if it already exists. So it seems like you saved me a whole bunch of time.

I am using ubuntu 16.04  ( and a tinker-board which has similar architecture to the pi ). It gives me an error about the gcc version that the tensorflow was compiled in. From some research on the web I found the issue is that the whl was compiled on older versions of debian. 

If you can, it would be very nice if you can also perform the same procedures on a rasbery pi running an ubuntu 16.04 ( you can do this with a chroot if needed ). Ubuntu 16.04 LTS is by far the most prevalent linux distro ( until 18.04 takes over ) so it seems like it will be relevant for a lot of users hopefully. 

Thanks in advance,
Dan

**Comment by lhelontra** [comment]
Hi, I'm glad to help you. All whell files was compiled with gcc linaro 6.3 for cross-compiling, maybe your problem is a glib version. What error appears when you install the whl file?

**Comment by hahmed0808** [comment]
For tensorflow 1.4.0 and above the installation completes but when it is run, tensorflow gives an error asking for glibc 2.23. Hope this helps.

**Comment by lhelontra** [comment]
Try compile inside docker:

```
FROM ubuntu:16.04

RUN dpkg --add-architecture armhf
RUN apt-get update
RUN apt-get install -y \
    autoconf \
    automake \
    curl \
    g++ \
    git \
    libtool \
    make \
    python \
    unzip \
    wget \
    zlib1g-dev \
    libpython-all-dev:armhf \
    libpython3-all-dev:armhf

RUN (cd /root && git clone https://github.com/lhelontra/tensorflow-on-arm)
WORKDIR /root
```

**Comment by liuqun** [comment]
@danFromTelAviv @hahmed0808 

Since #23 , there is a `Dockerfile` shipped with our project now!
Help us to improve the docker image if it works for you!
