### ISSUE TITLE
CompileError: command 'arm-linux-gnueabihf-gcc' failed with exit status 4

### ISSUE THREAD

**Issue by EddieOne** [lhelontra/tensorflow-on-arm#14]
I'm trying to install on Pi b3+ and getting an error. I tried to manually install grpcio but it didn't fix the problem. Here is the full error.

```
CompileError: command 'arm-linux-gnueabihf-gcc' failed with exit status 4



----------------------------------------
  Rolling back uninstall of grpcio
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-KA5EiS/grpcio/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-Icbf3Z-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-KA5EiS/grpcio
```

**Comment by lhelontra** [comment]
Hi, I'm using in rpi3 and not got this error, but try install tensorflow whl file without dependencies: `pip install <whl> --no-deps` and resolves the others dependencies without grpcio after tensorflow installation.
If you got another error, put here the full log.

**Comment by EddieOne** [comment]
I tried with `--no-deps` but it returned without error. I ended reinstalling raspbian and found some [other JDK instructions](https://www.raspberrypi.org/forums/viewtopic.php?t=197824#p1237329) where necessary to install the TF deps.

**Comment by FuriosoJack** [comment]
For those that have not worked at all you have to install these packages 

`sudo apt-get install libzbar-dev libzbar0`

**Comment by matthieut59** [comment]
C:\Users\mtourlouse
λ python debugsamsung.py
using saved token: 16339238
incoming message: {"data":{"clients":[{"attributes":{"name":"c2Ftc3VuZ2N0bA==","token":"16339238"},"connectTime":1548617774063,"deviceName":"c2Ftc3VuZ2N0bA==","id":"86b972e5-45a7-4390-85eb-eee6f2f9c0a8","isHost":false}],"id":"86b972e5-45a7-4390-85eb-eee6f2f9c0a8"},"event":"ms.channel.connect"}

Access granted.
Access granted.
Websocket closed
Traceback (most recent call last):
  File "debugsamsung.py", line 64, in <module>
    remote.connect_upnp()
  File "C:\Users\mtourlouse\AppData\Local\Programs\Python\Python37-32\lib\site-packages\samsungctl-0.8.0b0-py3.7.egg\samsungctl\upnp\UPNP_Device\upnp_class.py", line 128, in __getattr__
    if item in self.__devices:
  File "C:\Users\mtourlouse\AppData\Local\Programs\Python\Python37-32\lib\site-packages\samsungctl-0.8.0b0-py3.7.egg\samsungctl\upnp\UPNP_Device\upnp_class.py", line 128, in __getattr__
    if item in self.__devices:
  File "C:\Users\mtourlouse\AppData\Local\Programs\Python\Python37-32\lib\site-packages\samsungctl-0.8.0b0-py3.7.egg\samsungctl\upnp\UPNP_Device\upnp_class.py", line 128, in __getattr__
    if item in self.__devices:
  [Previous line repeated 496 more times]
RecursionError: maximum recursion depth exceeded

**Comment by easyyu** [comment]
> 
> 
> For those that have not worked at all you have to install these packages
> 
> `sudo apt-get install libzbar-dev libzbar0`

Thank you..it solved my problem with instaling: 
`pip install matpathlib`
