### ISSUE TITLE
how do you fix this?

### ISSUE THREAD

**Issue by 3073** [lhelontra/tensorflow-on-arm#15]
Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170124] on linux
Type "copyright", "credits" or "license()" for more information.
>>> 
=============== RESTART: /home/pi/Documents/camerafeed/Run.py ===============

Warning (from warnings module):
  File "/usr/lib/python3.5/importlib/_bootstrap.py", line 222
    return f(*args, **kwds)
RuntimeWarning: compiletime version 3.4 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.5

Warning (from warnings module):
  File "/usr/lib/python3.5/importlib/_bootstrap.py", line 222
    return f(*args, **kwds)
RuntimeWarning: builtins.type size changed, may indicate binary incompatibility. Expected 432, got 412

**Comment by lhelontra** [comment]
What whl file you installed and model of your raspberry pi?

**Comment by 3073** [comment]
Rpi Model: RP3
tensorflow-1.8.0-cp35-none-linux_armv7l.whl

**Comment by lhelontra** [comment]
I downloaded last raspbian image (2018-06-27-raspbian-stretch-lite.img), but not got this warnings.
Checks the md5 of whl file, type this command:
`md5sum tensorflow-1.8.0-cp35-none-linux_armv7l.whl`
Expected results are:
`d4c00d1d1cf7651daa22356d5547191f  tensorflow-1.8.0-cp35-none-linux_armv7l.whl`

**Comment by 3073** [comment]
I do not get the idea... could you elaborate it?

**Comment by lhelontra** [comment]
Type in shell:

```
$ wget https://github.com/lhelontra/tensorflow-on-arm/releases/download/v1.9.0/tensorflow-1.9.0-cp35-none-linux_armv7l.whl -P /tmp/
$ md5sum /tmp/tensorflow-1.9.0-cp35-none-linux_armv7l.whl

# expected output:
$  f4a9968dbc2ce0b99a4da8979a123a91  /tmp/tensorflow-1.9.0-cp35-none-linux_armv7l.whl

# trying install whl file:
$ pip install  /tmp/tensorflow-1.9.0-cp35-none-linux_armv7l.whl

# test if tensorflow it's ok
$ python3 -c "import tensorflow"
```

**Comment by lhelontra** [comment]
if you have another question, reopen this issue ;)

**Comment by hatemahmoudi** [comment]
#lhelontra when i trying install wh1 file  with he command  " pip install  /tmp/tensorflow-1.9.0-cp35-none-linux_armv7l.whl"
i had this error : 
pip install  /tmp/tensorflow-1.9.0-cp35-none-linux_armv7l.whlTraceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    from pip import main
ImportError: cannot import name main

**Comment by IvanTodorov910812** [comment]
[https://ibb.co/481PmT1](https://ibb.co/481PmT1)
The Same problem after i written " pip install /tmp/tensorflow-1.9.0-cp35-none-linux_armv7l.whl",
How can update the version 3.4 of module 'tensorflow.python.framework.fast_tensor_util' to 3.5

**Comment by lhelontra** [comment]
Try reinstall pip package:
```
sudo apt-get install --reinstall python3-pip
```

**Comment by IvanTodorov910812** [comment]
Thanks for the speedy answer, my first error is here > [https://ibb.co/SJ0Cztp](https://ibb.co/SJ0Cztp),
but if try to check the versions they are the same... > [https://ibb.co/9sfVn5Z](https://ibb.co/9sfVn5Z)
and then the output [https://ibb.co/RNR9zzb](https://ibb.co/RNR9zzb)

Should I also reinstall...?

**Comment by lhelontra** [comment]
first image is not error, but an warning. Because the tensorflow-1.9.0-cp35-none-linux_armv7l.whl not for python3.5 but for python3.4. 
third image is issue of pip, not tensorflow. https://github.com/pypa/pip/issues/5447

Try reinstall pip and install tensorflow package.

```
sudo dpkg -P python3-pip
sudo apt-get install python3-pip
wget https://github.com/lhelontra/tensorflow-on-arm/releases/download/v1.13.1/tensorflow-1.13.1-cp35-none-linux_armv7l.whl
sync
pip3 install tensorflow-1.13.1-cp35-none-linux_armv7l.whl
```

**Comment by IvanTodorov910812** [comment]
10x Fixed!!, -> but now a new Error occurred 
[https://ibb.co/FWT12Rd](https://ibb.co/FWT12Rd)

**Comment by IvanTodorov910812** [comment]
FIXED!!!

**Comment by gordonsolar** [comment]
Hi,

>sudo dpkg -P python3-pip
>sudo apt-get install python3-pip
>wget https://github.com/lhelontra/tensorflow-on-arm/releases/download/v1.13.1/tensorflow-1.13.1-cp35-none-linux_armv7l.whl
>sync
>pip3 install tensorflow-1.13.1-cp35-none-linux_armv7l.whl

also fixed the issue for me for a system install, thanks.
But i dont understand where the difference is to the installation described in 
[https://www.tensorflow.org/install/pip](url)

I created a virtual env and issued the commang
`pip install https://github.com/lhelontra/tensorflow-on-arm/releases/download/v1.13.1/tensorflow-1.13.1-cp35-none-linux_armv7l.whl`
and it worked too :-)
So is the magic in the lhelontra-repository/whl?

**Comment by glennford49** [comment]
FIXED but on root access 
sudo pip install https://github.com/lhelontra/tensorflow-on-arm/releases/download/v1.13.1/tensorflow-1.13.1-cp35-none-linux_armv7l.whl
