### ISSUE TITLE
Exception Error Installing Tensorflow

### ISSUE THREAD

**Issue by CriticalFlaw** [lhelontra/tensorflow-on-arm#24]
I've been following [EdjeElectronics' tutorial](https://github.com/EdjeElectronics/TensorFlow-Object-Detection-on-the-Raspberry-Pi) on how to setup Tensorflow on my Raspberry Pi 1B. However I haven't gotten far as I get exception errors when issuing the following command to run the installation

`sudo pip3 install /home/pi/tf/tensorflow-1.8.0-cp35-none-linux_armv6l.whl`

Any help with this would be greatly appreciated!

```
Processing ./tensorflow-1.8.0-cp35-none-linux_armv6l.whl
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "/usr/lib/python3/dist-packages/pip/download.py", line 809, in unpack_url
    unpack_file_url(link, location, download_dir, hashes=hashes)
  File "/usr/lib/python3/dist-packages/pip/download.py", line 715, in unpack_file_url
    unpack_file(from_path, location, content_type, link)
  File "/usr/lib/python3/dist-packages/pip/utils/__init__.py", line 617, in unpack_file
    flatten=not filename.endswith('.whl')
  File "/usr/lib/python3/dist-packages/pip/utils/__init__.py", line 502, in unzip_file
    zip = zipfile.ZipFile(zipfp, allowZip64=True)
  File "/usr/lib/python3.5/zipfile.py", line 1026, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.5/zipfile.py", line 1094, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

**Comment by lhelontra** [comment]
Hi, 
I tested on my rpi-zero, probably your whl file was corrupted.
Checks the md5 of whl file:
```
# download whl file
wget https://github.com/lhelontra/tensorflow-on-arm/releases/download/v1.8.0/tensorflow-1.8.0-cp35-none-linux_armv6l.whl -P /tmp/

# checks the md5 of file
md5sum /tmp/tensorflow-1.8.0-cp35-none-linux_armv6l.whl

# expected results:
e6e5a442769dbc9dc6b2b7b7666f1dd5  tensorflow-1.8.0-cp35-none-linux_armv6l.whl

# if ok, try install package
sudo pip3 install  /tmp/tensorflow-1.8.0-cp35-none-linux_armv6l.whl
```

**Comment by CriticalFlaw** [comment]
Thanks! No idea why all the previous downloads ended up corrupt but at least it's doing the installation now. It's been stuck on `Running setup.py bdist_wheel for numpy ...` for a few hours now, either it's just being really slow or I'll need to restart the process.

**Comment by lhelontra** [comment]
hmm... numpy probably is compiling. If you wants test the whl file, install tensorflow without dependencies and install numpy package via apt-get:

```
sudo pip3 install --no-deps /tmp/tensorflow-1.8.0-cp35-none-linux_armv6l.whl
sudo apt-get update && apt-get install python3-numpy
```

**Comment by liuqun** [comment]
@CriticalFlaw 

`pip install numpy` used to take ages, and now it’s super fast if you update to any resent version of Raspbian or in old version of Raspbian you may type:
```
sudo pip3 install numpy --extra-index-url https://www.piwheels.org/simple
```
See: https://www.raspberrypi.org/blog/piwheels/

---

https://www.tensorflow.org/install/install_raspbian suggest us to install libatlas, because:
> Atlas is a linear algebra library that numpy depends on, and so needs to be installed before TensorFlow. To add it to your system, run the following command:
`sudo apt-get install libatlas-base-dev`

But I prefer `apt-get install libatlas3-base` without the `dev` headers. It works for me either.

**Comment by CriticalFlaw** [comment]
Thanks again, I'm continuing to go through the installation without any issues (so far). Things are taking a while but it's all good and not related tensorflow anymore.
