### ISSUE TITLE
Add link to official tensorflow wheels

### ISSUE THREAD

**Issue by bennuttall** [lhelontra/tensorflow-on-arm#27]
Hi - thanks for going to the effort of building tensorflow for Raspberry Pi.

The TF team now officially support Raspberry Pi and have released wheels to [piwheels.org](https://www.piwheels.org/) (we automate building all packages on PyPI and provide a repo of arm wheels for Raspbery Pi).

See the announcements here:
- https://medium.com/tensorflow/tensorflow-1-9-officially-supports-the-raspberry-pi-b91669b0aa0
- https://blog.piwheels.org/official-tensorflow-releases/

So I just thought perhaps you could add a note to the README that TF is officially supported now and you can install it with `pip install tensorflow`.

Thanks again

**Comment by lhelontra** [comment]
Hi, i just added.
Thanks for information.
