### ISSUE TITLE
Illegal Instruction error when load trained model

### ISSUE THREAD

**Issue by kevinpei2001** [lhelontra/tensorflow-on-arm#32]
I tried to install tensorflow 1.4, 1.5, 1.8, 1.9 to my ARTIK 530 board. When I loaded the trained model from another PC (tensorflow-GPU trained). 

from keras.models import load_model
import numpy as np
model = load_model('./keras_trained_model.h5')

It always reported: 

Using TensorFlow backend.
Illegal instruction

Any ideas?

Kevin

**Comment by lhelontra** [comment]
Hi, probably wheel's files in this project is incompatible with instructions for artik 530 board. Needs compile tensorflow for cortex-A9.

**Comment by xiongmingzhi** [comment]
> I tried to install tensorflow 1.4, 1.5, 1.8, 1.9 to my ARTIK 530 board. When I loaded the trained model from another PC (tensorflow-GPU trained).
> 
> from keras.models import load_model
> import numpy as np
> model = load_model('./keras_trained_model.h5')
> 
> It always reported:
> 
> Using TensorFlow backend.
> Illegal instruction
> 
> Any ideas?
> 
> Kevin

how can you solve this promble?
