### ISSUE TITLE
ARM NN SDK

### ISSUE THREAD

**Issue by madhavajay** [lhelontra/tensorflow-on-arm#33]
Is there any interest in adding this:
https://developer.arm.com/technologies/machine-learning-on-arm/developer-material/how-to-guides/configuring-the-arm-nn-sdk-build-environment-for-tensorflow/single-page

I assume it would add considerable performance improvements for the operations that are currently supported.

**Comment by lhelontra** [comment]
Cool, i'll read this and see howto integrate in tf-arm project.
