### ISSUE TITLE
Runetime Warning in tensorflow with Raspberry Pi 1 model B

### ISSUE THREAD

**Issue by Ragnarok1988** [lhelontra/tensorflow-on-arm#36]
When i want to use tensorflow on my raspberry pi 1, I have the following problem:
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: compiletime version 3.4 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.5
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: builtins.type size changed, may indicate binary incompatibility. Expected 432, got 412
  return f(*args, **kwds)

I have Python 3.5.3 and i install tensorflow (1.11) with the following command:
sudo python3 -m pip install --no-cache-dir tensorflow

Thx for the help!

**Comment by lhelontra** [comment]
You're install tensorflow from piwheels., probably the tensorflow whl file was corrupted. Try install again.
