### ISSUE TITLE
Any plans to add version 1.12?

### ISSUE THREAD

**Issue by leoheck** [lhelontra/tensorflow-on-arm#38]
Any plans to add version 1.12 for py3.5 armv7l?

**Comment by lhelontra** [comment]
Yeah, i not build yet because the option for disable aws S3 support was removed, causing failed when import tensorflow. I not find yet another way for disable this feature, sorry.

**Comment by leoheck** [comment]
That's ok. If I have time soon, I will give a try to build it too.

**Comment by jackmitch** [comment]
I had a crack at this and a couple of things I found:

- We need a fairly recent master build for new config options to disable aws/hdfs (https://github.com/jackmitch/tensorflow-on-arm/commit/0dbe90574006be8542a0a13ab988bde18f7bb364)

- Recent master causes an internal compiler fault somewhere in Eigen

- Bumping the compiler to 7.3.1 causes build failures relating to GLIBC macros

- Bazel needs bumping to 0.18.0 at minimum

I haven't gotten any further and I assume these are probably compiler/glibc bugs from the Linaro distributed GCC so I'm not sure if filing issues over at tensorflow would help. Any suggestions for these appreciated.

**Comment by leoheck** [comment]
Actually, I am not familiar with tensorflow.

What is this aws/hds that you want to disable? 
And why you want to do that? 

I am trying to build it right now to see what happens.

**Comment by lhelontra** [comment]
The aws [S3](https://www.tensorflow.org/deploy/s3) support, when enabled, causes undefined symbol error. [hdfs](https://www.tensorflow.org/deploy/hadoop) also error.

**Comment by jackmitch** [comment]
Someone has back ported the aws/hdfs patches I was referring to https://github.com/muendelezaji/tensorflow-on-arm.

I tested this on the rpi config and can confirm that it compiles and works, see https://github.com/jackmitch/tensorflow-on-arm/tree/1.12-backport.

**Comment by lhelontra** [comment]
@jackmitch I tested too, works great.
