### ISSUE TITLE
How to build tensorflow 1.12.0 on Raspberry pi Python3.6? no use Docker.

### ISSUE THREAD

**Issue by chyidl** [lhelontra/tensorflow-on-arm#41]

**Comment by chyidl** [comment]
![image](https://user-images.githubusercontent.com/44197301/50510268-02e5e780-0ac4-11e9-89b8-24388d17c1e4.png)
Reference to previous related documents did not succeed, 
I Using Bazel (0.20.0) version. Please give any suggestion, Thank you first.

**Comment by lhelontra** [comment]
HI, open an issue in [bazel](https://github.com/bazelbuild/bazel) project.

**Comment by chyidl** [comment]
hi @lhelontra Thanks. it turned out to be a problem with network proxy.

**Comment by chyidl** [comment]
@lhelontra Thanks, bazel issue, It turned out to be a problem with network proxy.
