### ISSUE TITLE
Tensorboard

### ISSUE THREAD

**Issue by warp1337** [lhelontra/tensorflow-on-arm#42]
I built Tensorflow 1.6.0 for arm (Odroid UX4Q) successfully. However, when I am running:

`pip2 install --install-option="--prefix=$prefix" /tmp/tensorflow_pkg/tensorflow-1.6.0-cp27-cp27mu-linux_armv7l.whl  --upgrade --ignore-installed`

I am getting the following error message:

`  Could not find a version that satisfies the requirement tensorboard<1.7.0,>=1.6.0 (from tensorflow==1.6.0) (from versions: )
No matching distribution found for tensorboard<1.7.0,>=1.6.0 (from tensorflow==1.6.0)
`

Which seems reasonable since there is no tensorboard pip package for arm... Is there a workaround for it?

Thanks!

**Comment by lhelontra** [comment]
HI, install the pip without dependencies: 
```pip install /tmp/tensorflow_pkg/tensorflow-1.6.0-cp27-cp27mu-linux_armv7l.whl --no-deps```

**Comment by warp1337** [comment]
> HI, install the pip without dependencies:
> `pip install /tmp/tensorflow_pkg/tensorflow-1.6.0-cp27-cp27mu-linux_armv7l.whl --no-deps`

And install the deps manually, except Tensorboard?

/edit: Thanks that worked!
