### ISSUE TITLE
could you support tensorflow-1.12.0-cp36-none-linux_armv7l.whl? 

### ISSUE THREAD

**Issue by chyidl** [lhelontra/tensorflow-on-arm#44]
I want use my Raspberry Pi 3B+ to build Tensorflow Version (1.12.0) with bazel version (0.20.0) and Python3.6. but it's take a long time to failed..

**Comment by acu192** [comment]
I second this.

I naively tried the following:

```
# cd build_tensorflow/
# docker build -t tf-arm -f Dockerfile .
# docker run -it -v /tmp/tensorflow_pkg/:/tmp/tensorflow_pkg/ --env TF_PYTHON_VERSION=3.6 tf-arm ./build_tensorflow.sh ./configs/rpi.conf
```

(notice the `TF_PYTHON_VERSION=3.6` above; that's my only change)

It failed because it could not find a path to python. I forget the exact environment variable's name (something like `PYTHON_BIN_PATH`), but it ended up being an empty path thus it wasn't executable. Unfortunately I closed that terminal so I don't have the exact error on hand.

Is it possible to use this repo to build for python 3.6?

**Comment by lhelontra** [comment]
Hi, using crosscompiler, gcc linaro don't supports python version >= 3.6.

**Comment by chyidl** [comment]
<img width="1280" alt="screen shot 2018-12-30 at 11 16 41 pm" src="https://user-images.githubusercontent.com/44197301/50548518-32921c80-0c89-11e9-818a-3e059c059830.png">
Hi, I try to use Clang 6.0 buidling it. But have some error.

**Comment by chyidl** [comment]
**System information**

Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 9.6 (stretch)
Release:	9.6
Codename:	stretch
gcc: $ gcc -v
clang version 6.0.0 (tags/RELEASE_600/final)
Target: armv7l-unknown-linux-gnueabihf
Thread model: posix
InstalledDir: /usr/local/clang_6.0.0/bin
Found candidate GCC installation: /usr/lib/gcc/arm-linux-gnueabihf/4.6
Found candidate GCC installation: /usr/lib/gcc/arm-linux-gnueabihf/4.6.4
Found candidate GCC installation: /usr/lib/gcc/arm-linux-gnueabihf/4.7
Found candidate GCC installation: /usr/lib/gcc/arm-linux-gnueabihf/4.7.3
Found candidate GCC installation: /usr/lib/gcc/arm-linux-gnueabihf/4.8
Found candidate GCC installation: /usr/lib/gcc/arm-linux-gnueabihf/4.8.5
Found candidate GCC installation: /usr/lib/gcc/arm-linux-gnueabihf/4.9
Found candidate GCC installation: /usr/lib/gcc/arm-linux-gnueabihf/4.9.3
Found candidate GCC installation: /usr/lib/gcc/arm-linux-gnueabihf/5
Found candidate GCC installation: /usr/lib/gcc/arm-linux-gnueabihf/5.4.1
Found candidate GCC installation: /usr/lib/gcc/arm-linux-gnueabihf/6
Found candidate GCC installation: /usr/lib/gcc/arm-linux-gnueabihf/6.3.0
Selected GCC installation: /usr/lib/gcc/arm-linux-gnueabihf/6.3.0
Candidate multilib: .;@m32
Selected multilib: .;@m32
Python version 3.6.7
Build label: 0.20.0- (@non-git)

**Command triggering issue** 
```
$ bazel build -c opt --copt="-mfpu=neon-vfpv4" --copt="-funsafe-math-optimizations" --copt="-ftree-vectorize" --copt="-fomit-frame-pointer" --local_resources 1024,4.0,1.0 --verbose_failures tensorflow/tools/pip_package:build_pip_package --incompatible_remove_native_http_archive=false
```
Error Logs

<img width="1280" alt="screen shot 2018-12-30 at 11 16 41 pm" src="https://user-images.githubusercontent.com/44197301/50548748-2dcf6780-0c8d-11e9-9bfd-592a14823bb2.png">

**Comment by agjunyent** [comment]
+1 to this. I'm working with Odroid XU4 with Ubuntu 18.04, that comes with python3.6 by default.

I have to make lots of efforts to install both tensorflow and opencv, because tensorflow only supports python3.5, but opencv is not available by source on python3.5.

**Comment by ZAFERSHAMIM** [comment]
what should be bazel version for building  tensorflow 1.12 on raspberry pi 3b i just need compatible bazel version

**Comment by mihailescu2m** [comment]
I've created the dependencies for compiling tag 1.13.1 natively on the odroid xu4.
The config is conf/odroidxu4-native.conf, and build dependencies can be found in the Docker.bionic file at https://github.com/mihailescu2m/tensorflow-on-arm
