### ISSUE TITLE
tensorflow C library for arm

### ISSUE THREAD

**Issue by jewes** [lhelontra/tensorflow-on-arm#48]
Hello, 
Would you please also release the tensorflow C library (https://www.tensorflow.org/install/) for ARM? I suppose the C library is also built while building the python packages. Thanks!

**Comment by lhelontra** [comment]
Hi, edit your prefereble config, for example `configs/rpi.conf`
In line:
```BAZEL_EXTRA_FLAGS="--cpu=armeabi --crosstool_top=//tools/local_arm_compiler:toolchain //tensorflow/tools/pip_package:build_pip_package"```

Changes to:
```BAZEL_EXTRA_FLAGS="--cpu=armeabi --crosstool_top=//tools/local_arm_compiler:toolchain //tensorflow:libtensorflow.so //tensorflow:libtensorflow_framework.so //tensorflow/tools/pip_package:build_pip_package"```
