### ISSUE TITLE
How/Where did you set to use the Python 3.5?

### ISSUE THREAD

**Issue by leoheck** [lhelontra/tensorflow-on-arm#50]
Hi dude! (I am Br too haha)

How did you do to generate a tensorflow for python 3.5?
I tried to build it here, but the wheel is being created with the name `tensorflow-1.13.0rc2-cp34-none-linux_armv7l.whl`

I couldn't find where you set it. Can you point me that?

Also, I am not using your repo to build it, since it is not clear to me (looking the README.me) how to do that. 

I am doing the crosscompilation like tensorflow website tells to do.

**Comment by leoheck** [comment]
Also, do you know how can I limit the number of processors being used?

**Comment by leoheck** [comment]
My computer dies when I am using all the cores.

**Comment by lhelontra** [comment]
Hi dude!
Sorry for my delay.
```
git clone https://github.com/lhelontra/tensorflow-on-arm
cd tensorflow-on-arm/build_tensorflow/
docker build -t tf-arm -f Dockerfile .
docker run --name tf-arm -v /tmp/tensorflow_pkg/:/tmp/tensorflow_pkg/ -h tf-arm-builder -i -t tf-arm
docker start tf-arm
docker attach tf-arm
cd /root/tensorflow-on-arm/build_tensorflow/

# install nano for edit config target.
apt-get install nano

# for example, we using rpi.conf
pico configs/rpi.conf

# uncomment this lines and change the values:
# BAZEL_AVALIABLE_RAM=1536 # MB
# BAZEL_AVALIABLE_CPU=0.5  # number of cpu cores (1.0 epresenting single full core)
# BAZEL_AVALIABLE_IO=1.0   # workstation I/O capability (with 1.0 representing average workstation)

# save config file (ctrl+x -> y -> enter key) and build.
TF_PYTHON_VERSION=3.5 ./build_tensorflow.sh configs/rpi.conf
```

**Comment by leoheck** [comment]
Awsome!
