### ISSUE TITLE
two Exception error installing tensorflow

### ISSUE THREAD

**Issue by smaugdwyrm** [lhelontra/tensorflow-on-arm#53]
this error occurs when i do the "pip3 install tensorflow" command

Exception:Traceback (most recent call last):  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 594, in urlopen    chunked=chunked)  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 391, in _make_request    six.raise_from(e, None)  File "<string>", line 2, in raise_from  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 387, in _make_request    httplib_response = conn.getresponse()  File "/usr/lib/python3.5/http/client.py", line 1198, in getresponse    response.begin()  File "/usr/lib/python3.5/http/client.py", line 297, in begin    version, status, reason = self._read_status()  File "/usr/lib/python3.5/http/client.py", line 266, in _read_status    raise RemoteDisconnected("Remote end closed connection without"http.client.RemoteDisconnected: Remote end closed connection without responseDuring handling of the above exception, another exception occurred:Traceback (most recent call last):  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main    status = self.run(options, args)  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 353, in run    wb.build(autobuilding=True)  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 749, in build    self.requirement_set.prepare_files(self.finder)  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 380, in prepare_files    ignore_dependencies=self.ignore_dependencies))  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 554, in _prepare_file    require_hashes  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 278, in populate_link    self.link = finder.find_requirement(self, upgrade)  File "/usr/lib/python3/dist-packages/pip/index.py", line 465, in find_requirement    all_candidates = self.find_all_candidates(req.name)  File "/usr/lib/python3/dist-packages/pip/index.py", line 423, in find_all_candidates    for page in self._get_pages(url_locations, project_name):  File "/usr/lib/python3/dist-packages/pip/index.py", line 568, in _get_pages    page = self._get_page(location)  File "/usr/lib/python3/dist-packages/pip/index.py", line 683, in _get_page    return HTMLPage.get_page(link, session=self.session)  File "/usr/lib/python3/dist-packages/pip/index.py", line 792, in get_page    "Cache-Control": "max-age=600",  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 501, in get    return self.request('GET', url, **kwargs)  File "/usr/lib/python3/dist-packages/pip/download.py", line 386, in request    return super(PipSession, self).request(method, url, *args, **kwargs)  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 488, in request    resp = self.send(prep, **send_kwargs)  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 609, in send    r = adapter.send(request, **kwargs)  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/adapter.py", line 47, in send    resp = super(CacheControlAdapter, self).send(request, **kw)  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/adapters.py", line 423, in send    timeout=timeout  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 643, in urlopen    _stacktrace=sys.exc_info()[2])  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/util/retry.py", line 315, in increment    total -= 1TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'

**Comment by lhelontra** [comment]
This issue in pip, not tensorflow. Command above will be installing tensorflow by piwheels.
Download whl file using wget:
```
wget https://github.com/lhelontra/tensorflow-on-arm/releases/download/v1.13.1/tensorflow-1.13.1-cp35-none-linux_armv7l.whl
pip3 install tensorflow-1.13.1-cp35-none-linux_armv7l.whl
```
