### ISSUE TITLE
What is the problem? Tensorflow is not install

### ISSUE THREAD

**Issue by smalgan** [lhelontra/tensorflow-on-arm#54]
Help me pls !! I did not want to install it after I installed it with "wget". I tried pip3 again. Where is the error

![hata](https://user-images.githubusercontent.com/48032201/54782386-d4455c00-4c2f-11e9-857b-e132bd05c3d9.png)

**Comment by lhelontra** [comment]
perhaps is a incompatible python version. checks typing: ```python3 --version```
output should be like: ```Python 3.5.1```

**Comment by smalgan** [comment]
> belki de uyumsuz bir python versiyonu. yazarak denetler: `python3 --version`
> çıktı şöyle olmalıdır:`Python 3.5.1`


I've upgraded everything I'm using version 3.5. but I don't understand why it doesn't load.

**Comment by lhelontra** [comment]
try this commands:
```
wget https://github.com/lhelontra/tensorflow-on-arm/releases/download/v1.13.1/tensorflow-1.13.1-cp35-none-linux_armv7l.whl
pip3 install tensorflow-1.13.1-cp35-none-linux_armv7l.whl
```

**Comment by smalgan** [comment]
> bu komutları deneyin:
> 
> ```
> wget https://github.com/lhelontra/tensorflow-on-arm/releases/download/v1.13.1/tensorflow-1.13.1-cp35-none-linux_armv7l.whl
> pip3 install tensorflow-1.13.1-cp35-none-linux_armv7l.whl
> ```
not working
![Adsız123](https://user-images.githubusercontent.com/48032201/54785805-30ac7980-4c38-11e9-8636-e34874a87ab2.png)

**Comment by lhelontra** [comment]
your raspberry pi model is 2/3?

**Comment by Shiro97** [comment]
Hey lhelonhtra thanks a ton for such a helpful repo. I chose to do my project in college using TensorFlow on rpi (model - 3b , raspbian stretch 9) However I'm stuck with this error. It is important and my project review is coming up soon. Please help. 
I did the following commands till now 
```
wget https://github.com/lhelontra/tensorflow-on-arm/releases/download/v1.13.1/tensorflow-1.13.1-cp35-none-linux_armv7l.whl
pip3 install tensorflow-1.13.1-cp35-none-linux_armv7l.whl
```

Thanks a lot!
<img width="1264" alt="Screenshot 2019-04-17 at 11 34 51 AM" src="https://user-images.githubusercontent.com/37798320/56264856-6d6b7380-6105-11e9-8b45-8b502e4a8ccf.png">
<img width="1218" alt="Screenshot 2019-04-17 at 11 35 05 AM" src="https://user-images.githubusercontent.com/37798320/56264858-6f353700-6105-11e9-82e6-1add08bee36b.png">

**Comment by 3keepmovingforward3** [comment]
Try adding --user to pip3 install
pip3 install --user tensor.....

**Comment by Loongle** [comment]
Maybe you should use `sudo pip3 install ...`
