### ISSUE TITLE
Dockerfile is failing to build on branch v1.12.0

### ISSUE THREAD

**Issue by ghost** [lhelontra/tensorflow-on-arm#55]
I am trying to build the tensorflow v1.12.0 using the docker container on VM (Ubuntu 16.04). I was successful multiple times in the past. Recently, (today) I deleted the docker image tf-arm:latest that I was using previously and tried to make a clean build of tensorflow for RaspPi but unfortunately that is failing with this error. I am not sure if this is temporary server downtime or something that needs to be addressed permanently.
```
Err:9 http://httpredir.debian.org/debian jessie/main arm64 Packages
  404  Not Found
Ign:9 http://cdn-fastly.deb.debian.org/debian jessie/main arm64 Packages
Ign:16 http://cdn-fastly.deb.debian.org/debian jessie/non-free arm64 Packages
Ign:17 http://cdn-fastly.deb.debian.org/debian jessie/contrib arm64 Packages
Fetched 13.9 MB in 3s (3608 kB/s)
Reading package lists...
E: Failed to fetch http://httpredir.debian.org/debian/dists/jessie/main/binary-arm64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
The command '/bin/sh -c echo "deb http://httpredir.debian.org/debian/ jessie main contrib non-free" > /etc/apt/sources.list.d/jessie.list     && apt-get update && apt-get install -y libpng12-dev     && rm -f /etc/apt/sources.list.d/jessie.list     && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
```
Any suggestion as to what can be done to come up with a clean build with minimum effort ?

**Comment by zion302** [comment]
+1 had the same issue.

**Comment by lhelontra** [comment]
Edit the dockerfile and change this line:
```
RUN echo "deb http://httpredir.debian.org/debian/ jessie main contrib non-free" > /etc/apt/sources.list.d/jessie.list \
```
To:

```
RUN echo "deb http://ftp.us.debian.org/debian/jessie main contrib non-free" > /etc/apt/sources.list.d/jessie.list \
```

**Comment by vielmetti** [comment]
Jessie is LTS only, and there is no arm64 LTS support. The archive removal announcement is here:

https://lists.debian.org/debian-devel-announce/2019/03/msg00006.html
