### ISSUE TITLE
Error Regarding _FusedConv2D on ARMv6/Pi Zero

### ISSUE THREAD

**Issue by gcmike** [lhelontra/tensorflow-on-arm#59]
Hi there. I have successfully install v1.13.1 on pi zero with the armv6l.whl. I also have keras installed and ran an MNIST MLP example correctly with [KerasMNIST repo from EN10](https://github.com/EN10/KerasMNIST). But when I tried the cnn version of MNIST, some error regarding _FusedConv2D popped up. A bit researching [suggests](https://github.com/tensorflow/tensorflow/issues/24732) that the error is with the architecture. I have cross-checked with pi 3 and verified that the repo works on armv7.
According to the [comment](https://github.com/tensorflow/tensorflow/issues/24732#issuecomment-471536960) in the second link, cross-compiling with some setup will make it work. I was wondering if it is possible to release a new one with this feature?

**Comment by dudasdavid** [comment]
@gcmike I have the same issue on the zero, could you find a solution?

**Comment by marsmith** [comment]
Same here, looking for a solution

**Comment by dudasdavid** [comment]
@marsmith I could solve my issue with my LeNet-5 by turning off biasing in Conv2d operation.

See here:
https://github.com/tensorflow/tensorflow/issues/24732
