### ISSUE TITLE
could you support tensorflow-1.13.1-cp36-none-linux_armv7l.whl?

### ISSUE THREAD

**Issue by gordonsolar** [lhelontra/tensorflow-on-arm#60]
I am using python3.6 with my applications (especially asyncio) and would therefore like to install tensorflow with python3.6. 
With your wheel cp35 it works well with my raspberry pi 3. Is there a general problem with python3.6 and tensorflow?
On www.piwheels.org i found [https://www.piwheels.org/simple/tensorflow/tensorflow-1.13.1-cp36-none-linux_armv7l.whl](url) but i could not install it with pip. 
I got errors:

Building wheels for collected packages: h5py
  Building wheel for h5py (setup.py) ... error
  ERROR: Complete output from command /home/pi/tf_env/bin/python3.6 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-fu5ys8p_/h5py/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-oasnci4r --python-tag cp36:

**Comment by gordonsolar** [comment]
the problem installing 
[https://www.piwheels.org/simple/tensorflow/tensorflow-1.13.1-cp36-none-linux_armv7l.whl](url)
was h5py.
With 
`sudo apt-get install libhdf5-dev &&     sudo pip install h5py==2.9.0`
h5py was installed successfully
and then i could install tensorflow with
`pip3 install https://www.piwheels.org/simple/tensorflow/tensorflow-1.13.1-cp36-none-linux_armv7l.whl`

But again i get the error 

/home/pi/tf_env/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.4 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
/home/pi/tf_env/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: builtins.type size changed, may indicate binary incompatibility. Expected 432, got 412
  return f(*args, **kwds)

So a corrected wheel from you would be very helpfull

**Comment by gordonsolar** [comment]
I tried to cross compile to generate a wheel file myself with the official instruction - i got too many errors. Also with your version i do not succeed - to many errors and things i dont unterstand ...

**Comment by lhelontra** [comment]
Hi @gordonsolar ,
This output is not error, but warning. Because tensorflow was compiled for python 3.4 and renamed to 3.6.
```
/home/pi/tf_env/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.4 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
return f(*args, **kwds)
/home/pi/tf_env/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: builtins.type size changed, may indicate binary incompatibility. Expected 432, got 412
return f(*args, **kwds)
```

**Comment by lhelontra** [comment]
You can try compile for python 3.6 using dockerfile.buster
