### ISSUE TITLE
ImportError, undefined symbol

### ISSUE THREAD

**Issue by Flipajs** [lhelontra/tensorflow-on-arm#62]
Hi Leonardo, first of all, great job.

I get following error when using *tensorflow-1.14.0-cp35-none-linux_armv7l.whl* release

`ImportError: /home/filip/.local/lib/python3.5/site-packages/tensorflow/lite/python/interpreter_wrapper/_tensorflow_wrap_interpreter_wrapper.so: undefined symbol: _ZN6tflite12tensor_utils24NeonVectorScalarMultiplyEPKaifPf
`

I've been using previous version 1.13.1 without any issues. I am getting the same when I build it using docker. Any ideas?

System info: Raspbian 9, python 3.5.3

**Comment by lhelontra** [comment]
Hi @Flipajs , 
I thinking that issue: https://github.com/tensorflow/tensorflow/issues/24323

In tf 1.13.1, i fixed this issue with an patch, i will investigating this again. Thanks!

**Comment by muncok** [comment]
Hi @lhelontra 

I have the same issue at 1.14.0.

Does it also need some patches?

Thank you

**Comment by lhelontra** [comment]
I'm trying to apply the same patch that applies in tf 1.13.1. Loads tflite model but when allocate data, segmentation fault was happened.

**Comment by lhelontra** [comment]
I'm fixed this issue with an patch. This patch will'be available in next branch.

**Comment by lhelontra** [comment]
Tested with mobilenet from [mobilenet](http://download.tensorflow.org/models/mobilenet_v1_2018_08_02/mobilenet_v1_0.25_128_quant.tgz) and code bellow:
```
import tensorflow as tf
interpreter = tf.lite.Interpreter(model_path="mobilenet_v1_0.25_128_quant.tflite")
interpreter.allocate_tensors()
print(interpreter.get_input_details())
print(interpreter.get_output_details())
```

**Comment by muncok** [comment]
> Tested with mobilenet from [mobilenet](http://download.tensorflow.org/models/mobilenet_v1_2018_08_02/mobilenet_v1_0.25_128_quant.tgz) and code bellow:
> 
> ```
> import tensorflow as tf
> interpreter = tf.lite.Interpreter(model_path="mobilenet_v1_0.25_128_quant.tflite")
> interpreter.allocate_tensors()
> print(interpreter.get_input_details())
> print(interpreter.get_output_details())
> ```

It works well at tf 1.14.0
Thanks @lhelontra

**Comment by Flipajs** [comment]
I confirm. Works great. Thanks!
