### ISSUE TITLE
Could you support the python 3.7.x or 3.6.x?

### ISSUE THREAD

**Issue by SuzukiHonoka** [lhelontra/tensorflow-on-arm#64]
The default install version from apt is python 3.6.x,
I'd like to use the 3.6.x,
althought we can compile the 3.5 for my own,
but it takes too much time,
So,
As I said,
Hoping you could consider that,
Thanks!
Best wishes!

**Comment by lhelontra** [comment]
Hi @SuzukiHonoka ,
You can compile using Dockerfile.buster. Buster repository have python 3.6.

**Comment by SuzukiHonoka** [comment]
Thank you!
