### ISSUE TITLE
My solution for the problem of wrong "jessie debian repository"

### ISSUE THREAD

**Issue by muncok** [lhelontra/tensorflow-on-arm#65]
I found a solution at [link](https://github.com/MichaIng/DietPi/issues/2665#issuecomment-477348864)

And Jessie ARMv8 systems only: 
>` deb http://archive.debian.org/debian/ jessie main contrib non-free`

Please replace original dev repository address with the above

**Comment by lhelontra** [comment]
Hi @muncok,
Jessie repository no longer used.

**Comment by muncok** [comment]
> Hi @muncok,
> Jessie repository no longer used.

But, if I did not change it in Dockerfile, it causes an error in my case.

**Comment by lhelontra** [comment]
Sorry, you're right. i'm using jessie for install gcc-4. 
Thanks for your advice.
