### ISSUE TITLE
Also include C shared libraries build?

### ISSUE THREAD

**Issue by marianopeck** [lhelontra/tensorflow-on-arm#69]
Hi! 

Did you ever consider to add support to not only build the Python wheel but also a shared library? As far as I understand, everything is exactly the same except the line:

//tensorflow/tools/pip_package:build_pip_package

which should be:

//tensorflow/tools/lib_package:libtensorflow

This would help us all other language bindings (Go, Rust, etc) to have the shared library available...which is currently anywhere and you have to compile everything from scratch....  I am not pretending for all the available configs in `configs` but at least the one you do publish a Python wheel: https://github.com/lhelontra/tensorflow-on-arm/releases/tag/v1.14.0

Thoughts?

**Comment by marianopeck** [comment]
Hi, as I found no binary available, I had to manage myself.
I finally took the time to [write down everything I found during my attempt to get TensorFlow C library compiled for Raspberry Pi](https://dev.to/martinezpeck/challenge-accepted-build-tensorflow-c-binding-for-raspberry-pi-in-2019-4f89). In that tutorial, I point back to this issue in case you eventually start building shared libraries too. 
Best regards,

**Comment by lhelontra** [comment]
Hi @marianopeck
I distribute only whl files, if u want library and headers, append //tensorflow/tools/lib_package:libtensorflow in bazel options.

**Comment by marianopeck** [comment]
Hi @lhelontra
OK, what a pity :(   
If I fork the project and submit a PR with the necessary changes in `rpi.conf` (almost a one-liner) as well as confirming it works, would you be willing to merge and distribute it?

Thanks!

**Comment by JinmingYang5** [comment]
Hi @lhelontra  Could you share some of successfully built tensorflow c api packages for arm on github ?

**Comment by lhelontra** [comment]
Soon, i w'll publish tar file with wheel and c files.
