### ISSUE TITLE
Trouble using this to compile tensorflow lite

### ISSUE THREAD

**Issue by snowzach** [lhelontra/tensorflow-on-arm#72]
This repo works awesome to compile tensorflow but I am also trying to use it to compile tensorflow lite.  

Essentially I just edit the config file and replace `//tensorflow/tools/pip_package:build_pip_package` with `//tensorflow/lite:libtensorflowlite.so` 

It actually seems like it compiles fine but it doesn't link properly and errors with a bunch of `undefined reference to `tflite::tensor_utils::NeonYaddaYadda` errors. 

I found another post related to this https://github.com/tensorflow/tensorflow/issues/25120

I wasn't sure what to edit or if there was another flag I could pass to make it link properly.

Just curious if you or anyone else might have some ideas? I really don't get bazel totally.

**Comment by snowzach** [comment]
I figured out what the issue is, I think that it uses `cpu=armeabi` but in the tensorflow lite build stuff there is `armeabi-v7a` and `armv7a` but not targer for `armeabi` that includes the neon libraries. I think the easy fix is to change the cross compile stuff to use `cpu-armeabi` but I'm not sure what else that breaks.

**Comment by lhelontra** [comment]
In next branch have patch for fixes neon issues.
```git clone https://github.com/lhelontra/tensorflow-on-arm/
cd tensorflow-on-arm/build_tensorflow/
docker build -t tf-arm-buster -f Dockerfile .
docker run --name tf-arm-buster -it -v /tmp/tensorflow_pkg/:/tmp/tensorflow_pkg/ tf-arm-buster /bin/bash
git checkout next
```
edit your config file  and replace `//tensorflow/tools/pip_package:build_pip_package` with `//tensorflow/lite:libtensorflowlite.so` and build.

I'm testing edit the rpi.conf file, after build, ```libtensorflowlite.so``` can be found in ```bazel-bin/tensorflow/lite/libtensorflowlite.so```

**Comment by snowzach** [comment]
Yep, that worked! Thanks!

**Comment by snowzach** [comment]
Any other suggestions on how I can use this to build tensorflow lite without having to edit the config files?

**Comment by lhelontra** [comment]
You can try build from [source](https://www.tensorflow.org/lite/guide/build_arm64) or creates a new config for build tflite only.
