### ISSUE TITLE
"no registered kernels" on Rpi Zero

### ISSUE THREAD

**Issue by quappefeeder** [lhelontra/tensorflow-on-arm#74]
Hello There,
I have installed the wheel: "tensorflow-1.14.0-cp37-none-linux_armv6l.whl" on the Rpi Zero W, with Python3.7.
It is successfully installed. When I open my Python3.7 terminal, it can also "import tensorflow".
BUT... when I open another Programm with CNN algorithm, it shows the warning below.

```
tensorflow.python.framework.errors_impl.NotFoundError: No registered '_FusedConv2D' OpKernel for CPU devices compatible with node {{node activation_1/Relu}}
.  Registered:  <no registered kernels>

```
Is it because the CPU devices are not supported? How can I fix this problem? Is "from source compiling" a good solution?

Thanks!!

**Comment by lhelontra** [comment]
You can try [this](https://github.com/tensorflow/tensorflow/issues/24732)
