### ISSUE TITLE
segmentation fault on arm64 chip

### ISSUE THREAD

**Issue by skywo1f** [lhelontra/tensorflow-on-arm#76]
I am trying to run the basic tf-lite example :
https://www.tensorflow.org/lite/guide/inference#load_and_run_a_model_in_python
after installing the python 3.7 whl on an arm64 chip for tensorflow 1.14. It can load the model, But then segfaults at the allocating tensors stage. I have 4 gb ram on this chip, and have no problems using the regular model (non-tflite converted). I also ran that tflite model/example script on my pc, so I know that is not the problem.

**Comment by skywo1f** [comment]
I get the same issue when running it using python 3.5

**Comment by lhelontra** [comment]
you can past the output error and arm64 board model?
