### ISSUE TITLE
Support for Tensorflow 2.1.0

### ISSUE THREAD

**Issue by snowzach** [lhelontra/tensorflow-on-arm#81]
I have been using some of your scripts to help build my object detection platform DOODS for arm. (Thank your kindly) 

I was trying to add support for the latest Tensorflow RC. I was able to compile fine and it works great on x86 but having trouble with your scripts and Arm. It looks like they changed the way you have to specify the crosstool toolchain in bazel 0.27 which is required to build v2.1. I'm pretty dumb when it comes to bazel and don't really follow what needs to be changed. 

Are you planning on updating your patch for support of v2.1?

The error that comes up is:
```
ERROR: /opt/tensorflow/tools/local_arm_compiler/BUILD:28:1: //tools/local_arm_compiler:cc-compiler-local: missing value for mandatory attribute 'toolchain_config' in 'cc_toolchain' rule
ERROR: /opt/tensorflow/tools/local_arm_compiler/BUILD:40:1: //tools/local_arm_compiler:cc-compiler-armeabi: missing value for mandatory attribute 'toolchain_config' in 'cc_toolchain' rule
```

Anything I can do to help?

**Comment by lhelontra** [comment]
Hi, i working for solve this. At moment, build works, but fail when import tensorflow.

**Comment by Hmm466** [comment]
Looking forward to version 2.1.0

**Comment by EdjeElectronics** [comment]
Glad to hear you're working on it lhelontra! As usual, you're way ahead of Google with releasing TensorFlow packages that work on the Raspberry Pi :)

**Comment by nkhdiscovery** [comment]
> Hi, i working for solve this. At moment, build works, but fail when import tensorflow.

Great! Let me know how I may help, I am going to build 2.1.0 too.

**Comment by lhelontra** [comment]
@nkhdiscovery with debian buster  works, but fail with debian stretch

**Comment by lhelontra** [comment]
I just release tf 2.1.0 wheel's.
