### ISSUE TITLE
ImportError: /lib/arm-linux-gnueabihf/libm.so.6: version `GLIBC_2.23' not found

### ISSUE THREAD

**Issue by xiaoluojun** [lhelontra/tensorflow-on-arm#9]
I download tensorflow-1.5.0-cp27-none -linux_armv7l.whl to install on pi3. But I get a Error:ImportError: /lib/arm-linux-gnueabihf/libm.so.6: version `GLIBC_2.23' not found (required by /usr/local/lib/python2.7/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so)

Error tell that can't found version 'GLIBC_2.23', it is mean that I need upgrade my GLIBC.

Please help how upgrade it.

**Comment by lhelontra** [comment]
Sure, follow the steps below:

# creates a raspberry pi stretch repository
echo "deb http://archive.raspberrypi.org/debian/ stretch main ui" > /etc/apt/sources.list.d/rasp_stretch.list
echo deb http://mirrordirector.raspbian.org/raspbian/ stretch main contrib non-free rpi firmware >> /etc/apt/sources.list.d/rasp_stretch.list

# update and upgrade system
apt-get update
apt-get dist-upgrade

**Comment by xiaoluojun** [comment]
Thanks very much!
